DROP DATABASE IF EXISTS `timezone_db`;
CREATE DATABASE timezone_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `TZDB_ZONES_DETAILS`;
CREATE TABLE `TZDB_ZONES_DETAILS` (
  `COUNTRYCODE` varchar(2) NOT NULL,
  `COUNTRYNAME` varchar(100) NOT NULL,
  `ZONENAME` varchar(100) NOT NULL,
  `GMTOFFSET` bigint NOT NULL,
  `IMPORT_DATE` datetime NOT NULL,
  `DST` bigint NOT NULL,
  `ZONESTART` bigint NOT NULL,
  `ZONEEND` bigint NOT NULL,
  PRIMARY KEY (`ZONENAME`,`ZONESTART`,`ZONEEND`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;


DROP TABLE IF EXISTS `TZDB_TIMEZONES`;
CREATE TABLE `TZDB_TIMEZONES` (
  `COUNTRYCODE` varchar(2) NOT NULL,
  `COUNTRYNAME` varchar(100) NOT NULL,
  `ZONENAME` varchar(100) NOT NULL,
  `GMTOFFSET` bigint DEFAULT NULL,
  `IMPORT_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ZONENAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;


DROP TABLE IF EXISTS `TZDB_ERROR_LOG`;
CREATE TABLE `TZDB_ERROR_LOG` (
  `ERROR_DATE` datetime NOT NULL,
  `ERROR_MESSAGE` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;


DROP TABLE IF EXISTS `TZDB_ZONE_STAGES`;
CREATE TABLE `TZDB_ZONE_STAGES` (
  `ZONENAME` varchar(100) NOT NULL,
  `ACTION_DATE` datetime DEFAULT NULL,
  `COUNT` bigint DEFAULT NULL,
  PRIMARY KEY (`ZONENAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 DEFAULT COLLATE utf8_unicode_ci;

